# Generated by Django 3.1 on 2020-09-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ach',
            new_name='Achievements',
        ),
    ]
